# Generated by Django 5.2.9 on 2025-12-08 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_diagnosis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosis',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='diagnosis',
            old_name='lon',
            new_name='longitude',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='predicted_label',
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='disease',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='confidence',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='image',
            field=models.ImageField(upload_to='diagnoses/'),
        ),
    ]
